#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue May 30 14:46:17 2017

@author: taihuali
"""

import random
import numpy as np
import pandas as pd

dat = np.load('../SIFT_features.npy')
labels = pd.read_excel('../Labels.xlsx')

test_set = []
start = 0
end = 79
for i in range(0, 1360//80):
    test_set += random.sample(range(start, end), 10)
    start += 80
    end += 80

train = labels.iloc[list(set(range(0, 1360)) - set(test_set))]
test = labels.iloc[test_set]

train_writer = pd.ExcelWriter('../data/Training.xlsx')
test_writer = pd.ExcelWriter('../data/Testing.xlsx')
train.to_excel(train_writer, 'sheet1', index=False)
test.to_excel(test_writer, 'sheet1', index=False)
train_writer.save()
test_writer.save()